version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "github-actions "

  # Enable version updates for java
  - package-ecosystem: "maven"
    directory: "/application"
    # Check for updates once a day
    schedule:
      interval: "daily"
    target-branch: "dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "mvn "

  # Maintain dependencies for Python (Works recursively in application directories)
  - package-ecosystem: "pip"
    directory: "/infrastructure/stacks/postcode-etl/functions/uec-sf-postcode-extract"
    schedule:
      interval: "monthly"
    target-branch: "dependencies"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "pip "

  # Docker Dependencies
  - package-ecosystem: "docker"
    directory: "/build/docker/dos-postcode-api"
    schedule:
      interval: "daily"
    target-branch: "dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "docker "

  # Terraform Dependencies
  - package-ecosystem: "terraform"
    directory: "/infrastructure/stacks/datastore"
    schedule:
      interval: "monthly"
    target-branch: "dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "terraform "

  - package-ecosystem: "terraform"
    directory: "/infrastructure/stacks/firewall"
    schedule:
      interval: "monthly"
    target-branch: "dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "terraform "


  - package-ecosystem: "terraform"
    directory: "/infrastructure/stacks/postcode-etl"
    schedule:
      interval: "monthly"
    target-branch: "dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "terraform "

  - package-ecosystem: "terraform"
    directory: "/infrastructure/stacks/postcode-etl-sns"
    schedule:
      interval: "monthly"
    target-branch: "dependencies"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "terraform "
