spring:
  profiles:
    active: local
springdoc:
  api-docs:
    path: /postcode-api-docs

server:
  port: ${SERVER_PORT}
  ssl:
    key-store-type: PKCS12
    keystore: classpath:certificate/certificate.p12
    key-store-password:

dynamo:
  config:
    region: eu-west-2
  table:
    name: service-finder-local-postcode-location-mapping
  endpoint: http://host.docker.internal:8000/

invalid:
  postcode: Please enter a valid postcode
