server:
  port: ${SERVER_PORT}
  ssl:
    key-store-type: PKCS12
    keystore: classpath:certificate/${CERTIFICATE_DOMAIN}.p12
    key-store-password:

dynamo:
  config:
    region: eu-west-2
  table:
    name: ${DYNAMODB_POSTCODE_LOC_MAP_TABLE}
  endpoint: ${POSTCODE_LOCATION_DYNAMO_URL}

invalid:
  postcode: Please enter a valid postcode

api:
  version: 1.0
  title: NHS Postcode Mapping Application Interface
  description: NHS Postcode Mapping API provides northing and easting location coordinates for a given postcode
