springdoc:
  api-docs:
    path: /postcode-api-docs

server:
  port: ${SERVER_PORT}
  ssl:
    key-store-type: PKCS12
    keystore: classpath:certificate/certificate.p12
    key-store-password:

dynamo:
  config:
    region: eu-west-2
  table:
    name: ${DYNAMODB_POSTCODE_LOC_MAP_TABLE}
  endpoint: ${POSTCODE_LOCATION_DYNAMO_URL}

invalid:
  postcode: Please enter a valid postcode
