namespace: K8S_APP_NAMESPACE_TO_REPLACE

commonLabels:
  env: PROFILE_TO_REPLACE

commonAnnotations:
  splunk.com/index: eks_logs_service_finder_nonprod

resources:
  - namespace.yaml
  - service-deployment.yaml
  - service-alb.yaml
  - service-ingress.yaml
  - service-account-role.yaml
  - network-policy/default-deny-ingress.yaml
  - network-policy/allow-external-ingress.yaml

configMapGenerator:
  - name: uec-dos-api-pc-configmap
    literals:
      - SERVER_PORT=SERVER_PORT_TO_REPLACE
      - SPRING_PROFILES_ACTIVE=SPRING_PROFILES_ACTIVE_TO_REPLACE
      - POSTCODE_LOCATION_DYNAMO_URL=POSTCODE_LOCATION_DYNAMO_URL_TO_REPLACE
      - DYNAMODB_POSTCODE_LOC_MAP_TABLE=DYNAMODB_POSTCODE_LOC_MAP_TABLE_TO_REPLACE
