apiVersion: v1
kind: Service
metadata:
  name: uec-sf-pc-service
  namespace: K8S_APP_NAMESPACE_TO_REPLACE
  labels:
    app: uec-sf-pc
spec:
  type: ClusterIP
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: uec-sf-pc
