kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: uec-dos-api-pc-allow-external-ingress
spec:
  podSelector:
    matchLabels:
      app: uec-dos-api-pc
  ingress:
  - from: []
    ports:
    - protocol: TCP
      port: 443
