name: "Check code format and quality"
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check text files format
        run: |
          build/automation/etc/githooks/scripts/editorconfig-pre-commit.sh
      - name: Check Python files format
        run: |
          build/automation/etc/githooks/scripts/python-code-pre-commit.sh
      - name: Check Terraform files format
        run: |
          build/automation/etc/githooks/scripts/terraform-format-pre-commit.sh
      - name: Create coverage report
        run: |
          make compile coverage-report
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        working-directory: ./application
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=uec-dos-api-pca -Dsonar.organization=nhsd-exeter -Dsonar.java.binaries=target/classes -Dsonar.coverage.exclusions=src/main/java/**/config/*.*,src/main/java/**/model/*.*,src/main/java/**/exception/*.*,src/main/java/**/constants/*.*,src/main/java/**/interceptor/*.*,src/test/**/*.*,src/main/java/**/filter/*.*,src/main/java/**/PostcodeMappingApplication.* -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
